theme: jekyll-theme-cayman
title: Yorke Rigging
description: A provider of highwork Solutions
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
